# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 698334379737b3d328ad9b61c348f8b1be3aae83a92dcfd5da960d9c5e1eebe94bab114791ffa0aa764bb4bd156e3df1f3c3ba15c3b8864cf67b0ffdc77310a3

test:
  secret_key_base: 858f8081272af0d471dd841b52a9ac1418e8351d9e9c9f9ff621eedb0d4ee8d57ebb9f39b8c44341a5e191c8fbb68d8ff44c3731d1b50b86e96d71a379e750e8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
